### ISSUE TITLE
Provide BUFR and YAML files for AMSU-A

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/JEDI-Eval#55]
Provide sample BUFR files for AMSU-A for use with Ron's BUFR2IODA converter.

**Comment by CoryMartin-NOAA** [comment]
Using the following input BUFR file:
`/work/noaa/rstprod/dump/gdas.20201215/00/gdas.t00z.1bamua.tm00.bufr_d `
and the following YAML:
https://github.com/JCSDA-internal/ioda-converters/blob/develop/test/testinput/bufr_amsua_v2.yaml

I was able to produce a file, `gdas.t00z.1bamsua.tm00.nc` which at first glance seems reasonable.

@emilyhcliu do you know, is this YAML file correct? Are we currently able to /how do we split by platform? (i.e. AMSU-A N18, N19, etc. in different files)

**Comment by emilyhcliu** [comment]
@CoryMartin-NOAA  I have been working on the bufr to ioda conversion using Ron's feature/query.  The one you pointed to above is the current one in the develop.
[bufr_amsua_v2.yaml](https://github.com/JCSDA-internal/ioda-converters/blob/develop/test/testinput/bufr_amsua_v2.yaml) is a bit outdated.  I will open an PR and check in the updated amsua yaml file today.

**Comment by CoryMartin-NOAA** [comment]
thank you @emilyhcliu !
